services:
  app:
    build: .
    image: devops-mini:local
    ports:
      - "8000:8000"
    restart: unless-stopped
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
