name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest bandit

      - name: Run tests
        run: |
          bandit -q -r app || true
          pytest -q

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image to GHCR
        run: |
          OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"   # lowercase username/org
          IMAGE="ghcr.io/${OWNER_LC}/devops-mini"
          SHA_TAG="${GITHUB_SHA::7}"

          echo "Building $IMAGE:$SHA_TAG"
          docker build -t "${IMAGE}:${SHA_TAG}" .

          echo "Pushing $IMAGE:$SHA_TAG"
          docker push "${IMAGE}:${SHA_TAG}"

          echo "Tagging and pushing latest"
          docker tag "${IMAGE}:${SHA_TAG}" "${IMAGE}:latest"
          docker push "${IMAGE}:latest"
