name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps & run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest bandit
          bandit -q -r app || true
          pytest -q

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          IMAGE_SHA=ghcr.io/${{ github.repository_owner }}/devops-mini:${{ github.sha }}
          docker build -t $IMAGE_SHA .
          echo "IMAGE_SHA=$IMAGE_SHA" >> $GITHUB_ENV

      - name: Push image (sha and latest)
        run: |
          docker push $IMAGE_SHA
          LATEST=ghcr.io/${{ github.repository_owner }}/devops-mini:latest
          docker tag $IMAGE_SHA $LATEST
          docker push $LATEST
